## maintenance class
## 3-15-2026

# type hint imports
from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from technician import technician

# actual imports
import datetime


# used to generate maintenance requests
class maintenanceRequest:

    # full contructor
    def __init__(self, reason: str, techIn : technician) -> None:
        # used to track each request. generated by system
        # TODO : make system generate this ID
        self.maintenanceRequestID: str = "change me"
        # used to track when a request was made. set when maintenanceRequest was made
        self.dateRequested: datetime = datetime.datetime.now()
        # used to track when a request is resolved. Is set to 1-1-1900 till resolved
        self.dateResolved: datetime = datetime.datetime(1900, 1, 1)
        # used to record the reason for a request
        self.reasonForRequest: str = reason
        # used to track what technician goes with this maintenanceRequest
        self.assignedTechnician: technician = techIn

    ## simple update methods
    def updateMaintenanceRequestID(self, newID: str) -> None:
        self.maintenanceRequestID = newID

    def updateDateRequested(self, newDateRequested: datetime) -> None:
        self.dateRequested = newDateRequested

    def updateDateResolved(self, newDateResolved: datetime) -> None:
        self.dateResolved = newDateResolved

    def updateReasonForRequest(self, newReason: str) -> None:
        self.reasonForRequest = newReason

    def updateAssignedTechnician(self, newTech: technician) -> None:
        self.assignedTechnician = newTech

    ## simple return methods
    def returnMaintenanceRequestID(self) -> str:
        return self.maintenanceRequestID

    def returnDateRequested(self) -> datetime:
        return self.dateRequested

    def returnDateResolved(self) -> datetime:
        return self.dateResolved

    def returnReasonForRequest(self) -> str:
        return self.reasonForRequest

    def returnAssignedTechnician(self) -> technician:
        return self.assignedTechnician