## product class
## 3-15-2026

# type hint imports
from __future__ import annotations
from typing import TYPE_CHECKING
from typing import List

if TYPE_CHECKING:
    from machineSlot import machineSlot
    from machine import machine

# actual imports

# this is a class used to track a product information in the vending machine
class product:
    # constructor
    # *Doesnt make a new entry in assigned db table, only inits a class with this data. ID is assumed to correlate to a value inside the db table*
    def __init__(self, productIDIn: int, assignedMachineIn : machine, nameIn: str,  descIn: str, nutritIn: str, ingredIn: str, priceIn: float) -> None:
        # used to track productID. Generated by system
        # TODO : figure out ID generation
        self.productID: int = productIDIn
        # name of product
        self.name: str = nameIn
        # price of product, without tax
        self.price: float = priceIn
        # description of product, a short explanation of what it is
        self.description: str = descIn
        # the complete nutrition facts of a product
        self.nutritionFacts: str = nutritIn
        # the complete ingredient list for a product
        self.ingredients: str = ingredIn
        # the assigned machine for this product
        self.assignedMachine: machine = assignedMachineIn

    ## simple update methods
    def updateProductID(self, newID : str) -> None:
        self.productID = newID

    def updateName(self, newName: str ) -> None:
        self.name = newName

    def updatePrice(self, newPrice: float) -> None:
        self.price = newPrice
        
    def updateDescription(self, newDescription: str) -> None:
        self.description = newDescription
        
    def updateNutritionFacts(self, newNutritionFacts: str) -> None:
        self.nutritionFacts = newNutritionFacts

    def updateIngredients(self, newIngredients: str) -> None:
        self.ingredient = newIngredients

    def updateAssignedMachine(self, newMachine: machine) -> None:
        self.assignedMachine = newMachine
        
    ## simple return methods
    def returnProductID(self) -> str:
        return self.productID
        
    def returnName(self) -> str:
        return self.name
        
    def returnPrice(self) -> float:
        return self.price
        
    def returnDescription(self) -> str:
        return self.description
        
    def returnNutritionFacts(self) -> str:
        return self.nutritionFacts
        
    def returnIngredients(self) -> str:
        return self.ingredients
    
    def returnAssignedMachine(self) -> machine:
        return self.assignedMachine

