## product class
## 3-15-2026

# type hint imports
from __future__ import annotations
from typing import TYPE_CHECKING
from typing import List

if TYPE_CHECKING:
    from machineSlot import machineSlot

# actual imports

# this is a class used to track a product information in the vending machine
class product:
    # constructor
    def __init__(self, nameIn: str, priceIn: float, descIn: str, nutritIn: str, ingredIn: str, slotsIn: List[machineSlot], daysBeforeExpireIn: int) -> None:
        # used to track productID. Generated by system
        # TODO : figure out ID generation
        self.productID: str = "fix me"
        # name of product
        self.name: str = nameIn
        # price of product, without tax
        self.price: float = priceIn
        # description of product, a short explanation of what it is
        self.description: str = descIn
        # the complete nutrition facts of a product
        self.nutritionFacts: str = nutritIn
        # the complete ingredient list for a product
        self.ingredients: str = ingredIn
        # list of machine slots used to keep track of all the slots in the vending machine this product is currently in
        self.slots: List[machineSlot] = slotsIn
        # how many days before this product expires should it be restocked
        self.restockDaysBeforeExpire: int = daysBeforeExpireIn

    ## list update and return methods
    # append value to slots
    def appendSlot(self, newSlot: machineSlot) -> None:
        self.slots.append(newSlot)

    # replace value at index in slots with slot
    def replaceSlot(self, newSlot: machineSlot, index: int) -> None:
        self.slots[index] = newSlot

    # return value from slots list at index
    def returnSlot(self, index: int) -> machineSlot:
        return self.slots[index]

    # return entire slots list
    def returnSlots(self) -> List[machineSlot]:
        return self.slots

    ## simple update methods
    def updateProductID(self, newID : str) -> None:
        self.productID = newID

    def updateName(self, newName: str ) -> None:
        self.name = newName

    def updatePrice(self, newPrice: float) -> None:
        self.price = newPrice
        
    def updateDescription(self, newDescription: str) -> None:
        self.description = newDescription
        
    def updateNutritionFacts(self, newNutritionFacts: str) -> None:
        self.nutritionFacts = newNutritionFacts

    def updateIngredients(self, newIngredients: str) -> None:
        self.ingredient = newIngredients
        
    ## simple return methods
    def returnProductID(self) -> str:
        return self.productID
        
    def returnName(self) -> str:
        return self.name
        
    def returnPrice(self) -> float:
        return self.price
        
    def returnDescription(self) -> str:
        return self.description
        
    def returnNutritionFacts(self) -> str:
        return self.nutritionFacts
        
    def returnIngredients(self) -> str:
        return self.ingredients

