## product class
## 3-15-2026

# type hint imports
from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from unused.machine import machine

# actual imports
import mysql.connector

## setting up db cursor
machDB = mysql.connector.connect(
    host="localhost",
    user="interface",
    password="password",
    database = "vendingmachine"
)
cursor = machDB.cursor()

# this is a class used to track a product information in the vending machine
class product:
    # constructor
    # *Doesnt make a new entry in assigned db table, only inits a class with this data. ID is assumed to correlate to a value inside the db table*
    def __init__(self, productIDIn: int, assignedMachineIn : machine, nameIn: str,  descIn: str, nutritIn: str, ingredIn: str, priceIn: float) -> None:
        # used to track productID. Generated by system
        # TODO : figure out ID generation
        self.productID: int = productIDIn
        # name of product
        self.name: str = nameIn
        # price of product, without tax
        self.price: float = priceIn
        # description of product, a short explanation of what it is
        self.description: str = descIn
        # the complete nutrition facts of a product
        self.nutritionFacts: str = nutritIn
        # the complete ingredient list for a product
        self.ingredients: str = ingredIn
        # the assigned machine for this product
        self.assignedMachine: machine = assignedMachineIn

    ## simple update methods
    def updateName(self, newName: str ) -> None:
        self.name = newName
        cursor.execute("UPDATE `product` SET name = \"" + str(newName) + "\" WHERE productID = " + str(self.productID))
        machDB.commit()

    def updatePrice(self, newPrice: float) -> None:
        self.price = newPrice
        cursor.execute("UPDATE `product` SET price = \"" + str(newPrice) + "\" WHERE productID = " + str(self.productID))
        machDB.commit()
        
    def updateDescription(self, newDescription: str) -> None:
        self.description = newDescription
        cursor.execute("UPDATE `product` SET description = \"" + str(newDescription) + "\" WHERE productID = " + str(self.productID))
        machDB.commit()
        
    def updateNutritionFacts(self, newNutritionFacts: str) -> None:
        self.nutritionFacts = newNutritionFacts
        cursor.execute("UPDATE `product` SET nutritionfacts = \"" + str(newNutritionFacts) + "\" WHERE productID = " + str(self.productID))
        machDB.commit()

    def updateIngredients(self, newIngredients: str) -> None:
        self.ingredient = newIngredients
        cursor.execute("UPDATE `product` SET ingredients = \"" + str(newIngredients) + "\" WHERE productID = " + str(self.productID))
        machDB.commit()

    def updateAssignedMachine(self, newMachine: machine) -> None:
        self.assignedMachine = newMachine
        cursor.execute("UPDATE `product` SET machineid = \"" + str(newMachine.returnMachineID()) + "\" WHERE productID = " + str(self.productID))
        machDB.commit()
        
    ## simple return methods
    def returnProductID(self) -> str:
        return self.productID
        
    def returnName(self) -> str:
        return self.name
        
    def returnPrice(self) -> float:
        return self.price
        
    def returnDescription(self) -> str:
        return self.description
        
    def returnNutritionFacts(self) -> str:
        return self.nutritionFacts
        
    def returnIngredients(self) -> str:
        return self.ingredients
    
    def returnAssignedMachine(self) -> machine:
        return self.assignedMachine

